const A=[2,4,7,11,15,19,23,27,31],target=23;let step=4,timer=null,playing=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const states=[{l:0,r:8,m:4,op:"COMPARE"},{l:0,r:3,m:1,op:"DISCARD LEFT"},{l:2,r:3,m:2,op:"COMPARE"},{l:3,r:3,m:3,op:"NARROW"},{l:3,r:8,m:5,op:"DISCARD LEFT"},{l:6,r:8,m:7,op:"DISCARD RIGHT"},{l:6,r:6,m:6,op:"FOUND"},{l:6,r:8,m:7,op:"RETURN"},{l:6,r:6,m:6,op:"DONE"}];
const texts=["Start with the full sorted array. The middle value is 15. Because 15 < 23, the target must be to the right.","15 is smaller than 23, so the entire left portion can be discarded.","The next middle value is 4. It is smaller than 23, so continue to the right.","We have narrowed the candidate range. The next comparison moves toward the target.","We compared 23 with the middle value 19. Since 19 < 23, discard the left half including mid. New range → [6, 8].","The middle value is 27. Since 27 > 23, discard the right half.","The candidate is now index 6. We compare 23 with 23: target found.","Binary search has identified index 6. The algorithm can return this position.","Execution complete. Binary search found the target in O(log n) time."];
function render(){const s=states[step];$("#indexRow").innerHTML=A.map((_,i)=>`<span>${i}</span>`).join("");$("#arrayRow").innerHTML=A.map((v,i)=>`<div class="cell ${i===s.m?"mid":""} ${v===target?"target":""}">${v}</div>`).join("");$("#pointerRow").innerHTML=A.map((_,i)=>{let x="";if(i===s.l)x+=`<div class="pointer left">▲<br>left = ${s.l}</div>`;if(i===s.m)x+=`<div class="pointer mid">▲<br>mid = ${s.m}</div>`;if(i===s.r)x+=`<div class="pointer right">▲<br>right = ${s.r}</div>`;return x}).join("");$("#stepNo").textContent=step+1;$("#executionText").innerHTML=`<b>${s.op}</b> · ${texts[step]}`;$("#vars").innerHTML=[["arr","[2, 4, 7, 11, 15, 19, 23, 27, 31]"],["target","23"],["left",s.l],["right",s.r],["mid",s.m],["arr[mid]",A[s.m]]].map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td></tr>`).join("")}
function go(n){step=Math.max(0,Math.min(8,n));render()}function stop(){playing=false;clearInterval(timer);timer=null;$("#playBtn").textContent="▶ Play"}function play(){if(playing){stop();return}playing=true;$("#playBtn").textContent="Ⅱ Pause";timer=setInterval(()=>step>=8?stop():go(step+1),Math.max(300,1000/Number($("#speed").value)))}
$("#firstBtn").onclick=()=>go(0);$("#prevBtn").onclick=()=>go(step-1);$("#nextBtn").onclick=()=>go(step+1);$("#lastBtn").onclick=()=>go(8);$("#resetBtn").onclick=()=>{stop();go(0)};$("#playBtn").onclick=play;
$("#speed").oninput=e=>{$("#speedVal").textContent=Number(e.target.value).toFixed(1)+"x";if(playing){stop();play()}};
$("#answerBtn").onclick=()=>{$("#answer").classList.toggle("show");$("#answerBtn").textContent=$("#answer").classList.contains("show")?"Hide Answer":"Show Answer"};
function speak(t){if(!( "speechSynthesis" in window)){alert("Speech is not supported in this browser.");return}speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}
$("#listenBtn").onclick=()=>speak(texts[step]);$("#voiceTop").onclick=()=>speak("Welcome to DSA IQ 200. Predict the next state before pressing Next.");
$("#mobileMenu").onclick=()=>$("#sidebar").classList.toggle("open");
$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");$("#themeBtn").textContent=document.body.classList.contains("light")?"☾":"☼"};
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast((b.dataset.tab||b.textContent.trim())+' selected')});
$$('.teacher-tabs button').forEach(b=>b.onclick=()=>{$$('.teacher-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let m=b.textContent.trim(),q={Concept:'Binary Search requires a sorted array. Each comparison removes about half the remaining search space.',Step:texts[step],Why:'Sorted order proves that the discarded half cannot contain the target.',Socratic:'What property of the array makes it safe to eliminate half?',Hints:'Compare target with arr[mid], then keep the half that can still contain the target.'}[m];$('.speech').innerHTML=`<b>${m}</b><p>${q}</p>`});
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast((b.querySelector('span')?.textContent||b.textContent.trim())+' module selected')});
$$('.inspector-tabs span').forEach(b=>b.onclick=()=>{$$('.inspector-tabs span').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('Inspector: '+b.textContent.trim())});
$$('.arena-card button').forEach(b=>b.onclick=()=>{b.textContent='✓ Active';b.style.borderColor='#35d77d';toast(b.closest('.arena-card').querySelector('b').textContent+' started')});
$('.run').onclick=()=>{go(4);$('.code-actions span').textContent='✓ All tests passed';toast('Execution trace loaded')};
$$('.code-actions button:not(.run)').forEach(b=>b.onclick=()=>toast('Test cases: 8 / 8 passed'));
document.querySelector('.crumb button').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='☆'?'★':'☆';toast('Favorite updated')};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='/'){e.preventDefault();$('.global-search input').focus()}else if(e.key==='ArrowRight')go(step+1);else if(e.key==='ArrowLeft')go(step-1);else if(e.code==='Space'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();play()}});
function toast(msg){let t=$("#toast");if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1800)}
render();
